project: 
  type: website
  output-dir: docs
editor: source

website: 
  page-navigation: true
  title: "Ecologia Numérica" 

  page-footer:
    right: "Page built with [Quarto](https://quarto.org/) and [NOAA Quarto Simple Template](https://nmfs-opensci.github.io/NOAA-quarto-simple)"
    left: "&copy; [CC-1.0](content/LICENSE.txt)"

  sidebar:
    background: "#fd3412"
    logo: _logo7.jpg
    pinned: true
    align: center
    tools: 
      - icon: bank
        href: http://dgp.cnpq.br/dgp/espelhogrupo/28119
        text: "GDP CNPq"
      - icon: envelope
        href: mailto:elviomedeiros@servidor.uepb.edu.br
        text: "E-Mail"

    style: "docked"
    search: true

    collapse-level: 1
    contents:
      - href: index.qmd
        text: Inicio
      - href: https://elviomedeiros.quarto.pub/
        text: Base de teórica
      - href: content/3-01-rmd1_xlsx.qmd
        text: "R Módulo 1 - Importando planilhas de dados"
      - href: content/R_Modulo_6.qmd
        text: "R Módulo 6"
      - href: content/R_Modulo_7.qmd
        text: "R Módulo 7"
      - href: about.qmd
        text: Sobre este site

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

lang: "pt-br"
